name: Procesar Solicitudes de Colaborador

on:
  issues:
    types:
      - opened

jobs:
  procesar_solicitud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Procesar solicitud
      run: |
        print("processing")
